name: firebase_installations_dart
description: Pure Dart implementation of Firebase Installations API.
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0-dev.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  firebase_auth_dart: ^1.0.0
  firebase_core_dart: ^1.0.0
  firebaseapis: ^0.1.2
  http: ^0.13.4
  meta: ^1.7.0
  storagebox: ^0.1.0+1

dev_dependencies:
  test: ^1.16.0